In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))



# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/depression/student_depression_dataset.csv


In [2]:
df = pd.read_csv("/kaggle/input/depression/student_depression_dataset.csv")
print(df.head())
df_copy = df.copy()

   id  Gender   Age           City Profession  Academic Pressure  \
0   2    Male  33.0  Visakhapatnam    Student                5.0   
1   8  Female  24.0      Bangalore    Student                2.0   
2  26    Male  31.0       Srinagar    Student                3.0   
3  30  Female  28.0       Varanasi    Student                3.0   
4  32  Female  25.0         Jaipur    Student                4.0   

   Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0            0.0  8.97                 2.0               0.0   
1            0.0  5.90                 5.0               0.0   
2            0.0  7.03                 5.0               0.0   
3            0.0  5.59                 2.0               0.0   
4            0.0  8.13                 3.0               0.0   

        Sleep Duration Dietary Habits   Degree  \
0          '5-6 hours'        Healthy  B.Pharm   
1          '5-6 hours'       Moderate      BSc   
2  'Less than 5 hours'        Healthy       BA   
3     

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   id                                     27901 non-null  int64  
 1   Gender                                 27901 non-null  object 
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  object 
 4   Profession                             27901 non-null  object 
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  object 
 11  Di

In [4]:
df['Sleep Duration'].unique()

array(["'5-6 hours'", "'Less than 5 hours'", "'7-8 hours'",
       "'More than 8 hours'", 'Others'], dtype=object)

In [5]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [6]:
df['Sleep Duration'].value_counts()

Sleep Duration
'Less than 5 hours'    8310
'7-8 hours'            7346
'5-6 hours'            6183
'More than 8 hours'    6044
Others                   18
Name: count, dtype: int64

# Cleaning the Data

## Converting column 'Sleep Duration' to only numerical values.

In [7]:
## Converting column 'Sleep Duration' to only numerical values.

df['Sleep Duration'] = df['Sleep Duration'].str.strip("'").str.strip()


sleep_map = {
    "Less than 5 hours": 4,
    "5-6 hours": 5.5,
    "7-8 hours": 7.5,
    "More than 8 hours": 9,
    "Others": 5  # 5 beacause majorty of the values are 4 and less than that is 5.5
}

df['Sleep Duration (hours)'] = df['Sleep Duration'].map(sleep_map)



In [8]:
print(df.head())

   id  Gender   Age           City Profession  Academic Pressure  \
0   2    Male  33.0  Visakhapatnam    Student                5.0   
1   8  Female  24.0      Bangalore    Student                2.0   
2  26    Male  31.0       Srinagar    Student                3.0   
3  30  Female  28.0       Varanasi    Student                3.0   
4  32  Female  25.0         Jaipur    Student                4.0   

   Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0            0.0  8.97                 2.0               0.0   
1            0.0  5.90                 5.0               0.0   
2            0.0  7.03                 5.0               0.0   
3            0.0  5.59                 2.0               0.0   
4            0.0  8.13                 3.0               0.0   

      Sleep Duration Dietary Habits   Degree  \
0          5-6 hours        Healthy  B.Pharm   
1          5-6 hours       Moderate      BSc   
2  Less than 5 hours        Healthy       BA   
3          7-8

In [9]:
df['Sleep Duration (hours)'].unique()
# Done

array([5.5, 4. , 7.5, 9. , 5. ])

## Change 'Yes' and 'No' columns to 1 and 0

In [10]:
df['Family History of Mental Illness'].unique() # confirming the values in the column. 

array(['No', 'Yes'], dtype=object)

In [11]:
df['Have you ever had suicidal thoughts ?'].unique() # confirming the values column.

array(['Yes', 'No'], dtype=object)

In [12]:
yes_no_map = {"Yes":1, "No":0}

df['Suicidal Thoughts'] = df["Have you ever had suicidal thoughts ?"].map(yes_no_map)
df['Family History'] = df["Family History of Mental Illness"].map(yes_no_map)

In [13]:
print(df.head())

   id  Gender   Age           City Profession  Academic Pressure  \
0   2    Male  33.0  Visakhapatnam    Student                5.0   
1   8  Female  24.0      Bangalore    Student                2.0   
2  26    Male  31.0       Srinagar    Student                3.0   
3  30  Female  28.0       Varanasi    Student                3.0   
4  32  Female  25.0         Jaipur    Student                4.0   

   Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  ...  \
0            0.0  8.97                 2.0               0.0  ...   
1            0.0  5.90                 5.0               0.0  ...   
2            0.0  7.03                 5.0               0.0  ...   
3            0.0  5.59                 2.0               0.0  ...   
4            0.0  8.13                 3.0               0.0  ...   

  Dietary Habits   Degree Have you ever had suicidal thoughts ?  \
0        Healthy  B.Pharm                                   Yes   
1       Moderate      BSc                 

## Exploring and cleaning "Dietary Habits column"

In [14]:
df['Dietary Habits'].unique()

array(['Healthy', 'Moderate', 'Unhealthy', 'Others'], dtype=object)

In [15]:
df['Dietary Habits'].value_counts()

Dietary Habits
Unhealthy    10317
Moderate      9921
Healthy       7651
Others          12
Name: count, dtype: int64

In [16]:
diet_map = {
    'Unhealthy': 0,
    'Moderate': 1,
    'Healthy': 2,
    'Others': 0  # 0 because Majority of the sudents had unhealthy habits
}

df['Dietary Score'] = df['Dietary Habits'].map(diet_map)


In [17]:
print(df.head())

   id  Gender   Age           City Profession  Academic Pressure  \
0   2    Male  33.0  Visakhapatnam    Student                5.0   
1   8  Female  24.0      Bangalore    Student                2.0   
2  26    Male  31.0       Srinagar    Student                3.0   
3  30  Female  28.0       Varanasi    Student                3.0   
4  32  Female  25.0         Jaipur    Student                4.0   

   Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  ...   Degree  \
0            0.0  8.97                 2.0               0.0  ...  B.Pharm   
1            0.0  5.90                 5.0               0.0  ...      BSc   
2            0.0  7.03                 5.0               0.0  ...       BA   
3            0.0  5.59                 2.0               0.0  ...      BCA   
4            0.0  8.13                 3.0               0.0  ...   M.Tech   

  Have you ever had suicidal thoughts ? Work/Study Hours Financial Stress  \
0                                   Yes      

### Done cleaning.

# Exploring the Data

In [53]:




# # ✅ Optional, but improves Seaborn plot styling
# sns.set(style="whitegrid")


## Q1) Distribution of Depression Cases

In [64]:
import plotly.express as px

fig = px.histogram(df, x='Depression', nbins=2, title="Depression Count")
# fig.update_traces( textposition="outside")
# fig.update_layout(xaxis_tickangle=-45,xaxis_title='Depression (0 = No, 1 = Yes)', yaxis_title='Count',showlegend=False, template="plotly_dark")
fig.show()

Conclusion:
We can see that 16,336 students are depressed out of 27901 students. which means 58.54% Student are depressed out of 100%. This is very shocking as majority of the students are depressed in India which is the direct reflection of the short-comings of the Indian education education system and environment.

In [20]:
x=(16336/27901)*100
x

58.549872764417046

## Q2) Depression by Gender

In [56]:
fig = px.histogram(
    df,
    x="Gender",
    color="Depression",
    barmode="group",
    title="Depression Distribution by Gender",
    labels={"Gender": "Gender", "Depression": "Depression Status"}
)
fig.show()


In [22]:
df['Gender'].value_counts()

Gender
Male      15547
Female    12354
Name: count, dtype: int64

In [23]:
male_perc = (9115/15547)*100
female_per = (7221/12345)*100
print(male_perc,female_per)

58.62867434231684 58.49331713244228


Conclusion: There is no noticeable gap between percentage the male and female students who are in depression. This also suggests that the male and female population are affected equally by depression.

## Q3) CGPA vs Depression

In [57]:
import plotly.express as px

fig = px.box(df, x='Depression', y='CGPA', color='Depression',
             title='CGPA vs Depression')
fig.update_layout(xaxis_title='Depression', yaxis_title='CGPA')
fig.show()



In [25]:
# Calculate the Pearson correlation between CGPA and Depression
correlation = df['CGPA'].corr(df['Depression'])
print(f"Pearson Correlation between CGPA and Depression: {correlation}")


Pearson Correlation between CGPA and Depression: 0.022210470344461636


Conclusion: Based on this visualization alone, there doesn't appear to be a strong correlation between CGPA and depression status in this student population. Students with depression seem to achieve similar academic performance as measured by CGPA compared to students without depression.

## Q4) Academic & Work Pressure vs Depression

In [29]:
print(df['Academic Pressure'].unique())
print(df['Work Pressure'].unique())


[5. 2. 3. 4. 1. 0.]
[0. 5. 2.]


In [35]:
# Academic Pressue VS Depression

import plotly.express as px
import plotly.io as pio

# Recommended setting for Kaggle to enable camera icon
pio.renderers.default = "notebook_connected"

# Academic Pressure vs Depression
fig = px.box(
    df,
    x='Depression',
    y='Academic Pressure',
    color='Depression',
    title='Academic Pressure vs Depression',
    labels={
        "Depression": "Depression Status (0 = No, 1 = Yes)",
        "Academic Pressure": "Academic Pressure (0–5 Scale)"
    },
    points="all"  # shows all points for better understanding of spread
)
fig.update_layout(showlegend=False)
fig.show()



In [28]:
import plotly.express as px

# Create a scatter plot for CGPA vs Depression
fig = px.scatter(df, x="CGPA", y="Depression", title="CGPA vs Depression",
                 labels={"CGPA": "CGPA", "Depression": "Depression Status"})
fig.show()
